from typing import Dict, Any, List

FINANCE_CONCEPTS_REPOSITORY: List[Dict[str, Any]] = [
    {
        "concept": "Bond Duration",
        "explanation": "Duration measures how sensitive a bond's price is to changes in interest rates. A higher duration means bond prices fall more when interest rates rise.",
        "numerical_example": "A bond with a duration of 5 years will fall approximately 5% in price for a 1 percentage-point increase in yield.",
        "keywords": ["bond", "yield", "rate", "fed", "rbi", "g-sec", "treasury"]
    },
    {
        "concept": "Repo Rate Transmission",
        "explanation": "Repo rate transmission is the process by which central bank policy rate changes flow through commercial bank deposit and lending rates.",
        "numerical_example": "If the RBI cuts repo rate by 25 bps (0.25%), a bank lowering its home loan rate from 8.50% to 8.25% reduces a ₹50 Lakh loan EMI by ~₹800/month.",
        "keywords": ["rbi", "repo rate", "central bank", "bank", "lending", "credit"]
    },
    {
        "concept": "EBITDA Margin",
        "explanation": "EBITDA margin measures a company's operating profitability before capital structure, taxes, and non-cash depreciation expenses.",
        "numerical_example": "A company with ₹1,000 Cr revenue and ₹250 Cr EBITDA has a 25% EBITDA margin.",
        "keywords": ["earnings", "revenue", "profit", "margin", "quarterly", "tcs", "reliance"]
    },
    {
        "concept": "Weighted Average Cost of Capital (WACC)",
        "explanation": "WACC represents a company's required return on capital, blending equity costs and tax-shielded debt costs weighted by market value.",
        "numerical_example": "If a firm is funded 60% equity at 12% cost and 40% debt at 6% post-tax cost, its WACC is (0.60 * 12%) + (0.40 * 6%) = 9.6%.",
        "keywords": ["capital", "debt", "valuation", "investment", "dcf", "fundraising"]
    },
    {
        "concept": "Yield Curve Inversion",
        "explanation": "A yield curve inversion occurs when short-term interest rates exceed long-term yields, reflecting investor expectations of future central bank rate cuts.",
        "numerical_example": "When a 2-year Treasury yield is 4.5% while the 10-year yield is 4.0%, the 2s10s yield curve spread is inverted by -50 bps.",
        "keywords": ["yield curve", "treasury", "bonds", "recession", "g-sec"]
    },
    {
        "concept": "Price-to-Earnings Ratio (P/E)",
        "explanation": "P/E compares a stock's price to its annual per-share earnings, reflecting market expectations of future growth.",
        "numerical_example": "If a stock trades at ₹500 with EPS of ₹25, its P/E ratio is 20x.",
        "keywords": ["stock", "shares", "valuation", "pe ratio", "nifty", "sensex"]
    },
    {
        "concept": "Current Account Deficit (CAD)",
        "explanation": "CAD measures the net deficit when a country's total imports of goods, services, and transfers exceed its total exports.",
        "numerical_example": "If India imports $60B of goods/services but exports $50B in a quarter, it runs a $10B Current Account Deficit.",
        "keywords": ["india", "gdp", "trade", "import", "export", "rupee", "usd"]
    },
    {
        "concept": "Free Cash Flow (FCF)",
        "explanation": "FCF is the cash generated by operational activities remaining after paying for necessary capital expenditures (CapEx).",
        "numerical_example": "A company with ₹500 Cr operating cash flow and ₹150 Cr CapEx generates ₹350 Cr Free Cash Flow.",
        "keywords": ["cash flow", "fcf", "capex", "capital expenditure", "balance sheet"]
    }
]
